/** 最小结果窗口宽度 */
const MIN_RESULT_WINDOW_WIDTH = 220
/** 最小结果窗口高度 */
const MIN_RESULT_WINDOW_HEIGHT = 70
/** 结果弹窗操作栏高度 */
const RESULT_WINDOW_BAR_HEIGHT = 36

/** 截图窗口监听鼠标位置变化的间隔时间 */
const SCREENSHOT_WINDOW_LISTEN_MOUSE_POSITION_INTERVAL = 150

export const getConfig = () => {
  return {
    MIN_RESULT_WINDOW_WIDTH,
    MIN_RESULT_WINDOW_HEIGHT,
    RESULT_WINDOW_BAR_HEIGHT,
    SCREENSHOT_WINDOW_LISTEN_MOUSE_POSITION_INTERVAL,
  }
}
