export enum SendEnum {
  // 用于截图选择器
  SCREENSHOT_START = 'SCREENSHOT_START',
  SCREENSHOT_CANCEL = 'SCREENSHOT_CANCEL',
  SCREENSHOT_SELECTED = 'SCREENSHOT_SELECTED',
  DISPLAY_TRANSLATION_RESULT = 'DISPLAY_TRANSLATION_RESULT',
  RESULT_WINDOW_CLOSE = 'RESULT_WINDOW_CLOSE',
  /** 错误通知 */
  DISPLAY_NOTIFICATION = 'DISPLAY_NOTIFICATION',
  /** 错误通知窗口关闭 */
  CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION',

  /** 设置 */
  SET_LOCAL_FORAGE = 'SET_LOCAL_FORAGE',
  /** 初始化设置 */
  INIT_LOCAL_FORAGE = 'INIT_LOCAL_FORAGE'
} 