export enum SendEnum {
  // 用于截图选择器
  SCREENSHOT_START = 'SCREENSHOT_START',
  SCREENSHOT_CANCEL = 'SCREENSHOT_CANCEL',
  SCREENSHOT_SELECTED = 'SCREENSHOT_SELECTED',
  DISPLAY_TRANSLATION_RESULT = 'DISPLAY_TRANSLATION_RESULT',
  RESULT_WINDOW_CLOSE = 'RESULT_WINDOW_CLOSE',

  /** 设置 */
  SET_LOCAL_FORAGE = 'SET_LOCAL_FORAGE',
  /** 初始化设置 */
  INIT_LOCAL_FORAGE = 'INIT_LOCAL_FORAGE',
  /** 复制文本成功 */
  COPY_TEXT_SUCCESS = 'COPY_TEXT_SUCCESS',
  /** 英汉互译 */
  ENGLISH_CHINESE_TRANSLATION = 'ENGLISH_CHINESE_TRANSLATION',
  /** 英汉互译成功 */
  ENGLISH_CHINESE_TRANSLATION_SUCCESS = 'ENGLISH_CHINESE_TRANSLATION_SUCCESS',
  /** 英汉互译失败 */
  ENGLISH_CHINESE_TRANSLATION_FAIL = 'ENGLISH_CHINESE_TRANSLATION_FAIL',
  /** 设置开机自启动 */
  SET_AUTO_LAUNCH = 'SET_AUTO_LAUNCH',
  /** 交换内容 */
  SWAP_CONTENT = 'SWAP_CONTENT',
  /** 检查更新 */
  CHECK_UPDATE = 'CHECK_UPDATE',
  /* 检查完成 */
  CHECK_UPDATE_COMPLETE = 'CHECK_UPDATE_COMPLETE',
  /** 获取应用版本 */
  GET_APP_VERSION = 'GET_APP_VERSION',
  /** 检查更新结果 */
  CHECK_UPDATE_RESULT = 'CHECK_UPDATE_RESULT',
  /** 下载进度 */
  DOWNLOAD_PROGRESS = 'DOWNLOAD_PROGRESS',
  /** 下载失败 */
  DOWNLOAD_FAIL = 'DOWNLOAD_FAIL',
  /** 更新下载完成 */
  UPDATE_DOWNLOAD_COMPLETE = 'UPDATE_DOWNLOAD_COMPLETE',
  /* 重启更新 */
  RESTART_UPDATE_AND_INSTALL = 'RESTART_UPDATE_AND_INSTALL',
  /** 开始截图 */
  START_SCREENSHOT = 'START_SCREENSHOT',
  /** 打开外部链接 */
  OPEN_EXTERNAL_URL = 'OPEN_EXTERNAL_URL',
}
